CFLAGS_secfilter.o := -fno-strict-aliasing
CFLAGS_sec_filter.o := -fno-strict-aliasing
CFLAGS_tcp_track.o := -fno-strict-aliasing
CFLAGS_url_parser.o := -fno-strict-aliasing
obj-$(CONFIG_SEC_NET_FILTER) := secfilter.o
secfilter-y := sec_filter.o \
		tcp_track.o \
		url_parser.o 
