CFLAGS_atl1c_main.o := -fno-strict-aliasing
CFLAGS_atl1c_main_hw.o := -fno-strict-aliasing
CFLAGS_atl1c_ethtool.o := -fno-strict-aliasing
CFLAGS_atl1c_hw.o := -fno-strict-aliasing
obj-$(CONFIG_ATL1C) += atl1c.o
atl1c-objs := atl1c_main.o atl1c_hw.o atl1c_ethtool.o
